name: Deploy to GitHub Pages

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test-deploy:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - name: check to wiki-site
        run: cd apps/wiki-site
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Test build website
        run: pnpm run build
  deploy:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.MAC_DEPLOY }}
      - name: Deploy to GitHub Pages
        env:
          USE_SSH: true
        run: |
          git config --global user.email "jeiizou@qq.com"
          git config --global user.name "jeiizou"
          cd apps/wiki-site
          pnpm run install --frozen-lockfile
          pnpm run deploy
